project_name: ptt
builds:
  - id: ptt
    binary: ptt
    main: ./main.go
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/a-tarek/ptt/cmd.Version={{.Version}}
archives:
  - id: default
    format: binary
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
